pipeline {

  agent any
  
  stages {
    stage('Build') {
      steps {
            bat 'mvn -B -U -e -V -f mavenizecloudhubdeployment/pom.xml clean -DskipTests package'
      }
    }

     stage('Deployment') {
      steps {
           bat 'mvn -f mavenizecloudhubdeployment/pom.xml clean package -Pdev deploy -DmuleDeploy'
      }
    }
    
  }
}
